package fr.gouv.culture.an.eaccpf2rico.cli;

import java.io.ByteArrayOutputStream;
import java.io.File;

import javax.xml.transform.Transformer;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;

import org.apache.commons.io.FileUtils;

import fr.sparna.commons.xml.TransformerBuilder;

public class ErrorCodeXsltDocumentationGenerator {

	public static void main(String[] args) throws Exception {
		
		StringBuffer sb = new StringBuffer();
		sb.append("[_Home_](index.html) > XSLT Error Codes"+"\n");
		sb.append("# XSLT Error Codes"+"\n");
		sb.append("_note : this file is automatically generated from the XML eac2rico-codes.xml file._"+"\n");
		sb.append("\n");
		
		Transformer transformer = TransformerBuilder.createSaxonProcessor().createTransformer(new StreamSource(ErrorCodeXsltDocumentationGenerator.class.getResourceAsStream("/errorCodes2md.xslt")));
		ByteArrayOutputStream resultBa = new ByteArrayOutputStream();
		
		transformer.transform(
				new StreamSource(ErrorCodeXsltDocumentationGenerator.class.getResourceAsStream("/xslt/eac2rico-codes.xml")),
				new StreamResult(resultBa)
		);
		sb.append(resultBa.toString());

		File outputFile = new File(args[0]);
		FileUtils.write(outputFile, sb.toString(), "UTF-8");
	}
	
}
