package fr.gouv.culture.an.eaccpf2rico.cli;

import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;

import fr.gouv.culture.an.eaccpf2rico.Description;
import fr.gouv.culture.an.eaccpf2rico.ErrorCode;

public class ErrorCodeDocumentationGenerator {

	public static void main(String[] args) throws IOException {
		File outputFile = new File(args[0]);
		StringBuffer sb = new StringBuffer();
		sb.append("[_Home_](index.html) > Error Codes"+"\n");
		sb.append("# Error Codes"+"\n");
		sb.append("_note : this file is automatically generated from the source code._"+"\n");
		sb.append("\n");
		
		for (ErrorCode aCode : ErrorCode.values()) {			
			try {
				Description d = aCode.getClass().getField(aCode.name()).getAnnotation(Description.class);
				if(d != null) {
					sb.append("## "+aCode.name()+"\n");
					sb.append("  - code : "+d.notation()+"\n");
					sb.append("  - definition : "+d.definition()+"\n");
					sb.append("\n");
				}
			} catch (Exception e) {
				e.printStackTrace();
			}			
		}
		FileUtils.write(outputFile, sb.toString(), "UTF-8");
	}
	
}
